### ISSUE TITLE
JS breaks when asset pipeline is enabled

### ISSUE THREAD

**Issue by icewind1991** [owncloud/calendar#205]
When asset pipeline is enabled the resulting js throws a syntax error

**Comment by georgehrke** [comment]
The error happens in a third party component :confused: 

@icewind1991 are we sure this is not a bug in our minifier?

**Comment by georgehrke** [comment]
It seems to have issues with get and set in js

**Comment by georgehrke** [comment]
ping @icewind1991

**Comment by georgehrke** [comment]
might be related to this issue, not entirely sure though
https://github.com/tchwork/jsqueeze/blob/074a7ac403d1fae262fd662c43c04b62d71c3e50/tests/test/infinite.js.xfail

**Comment by georgehrke** [comment]
Just for the record:
<img width="895" alt="calendar - owncloud chromium today at 10 26 16 pm" src="https://cloud.githubusercontent.com/assets/1250540/13475958/d4e11b96-e0c5-11e5-9f43-cbc863202e25.png">

**Comment by georgehrke** [comment]
How to handle this issue?

Detect inside the ViewController if `asset-pipeline.enabled` is enabled and display an error page to the user, asking them to contact their admin to disable this config property?

cc @DeepDiver1975

**Comment by georgehrke** [comment]
It's very confusing that it fails here and not earlier already
https://github.com/owncloud/calendar/blob/master/js/vendor/ical.js/build/ical.js#L2576

**Comment by georgehrke** [comment]
Sorry, it fails here already.
https://github.com/owncloud/calendar/blob/master/js/vendor/ical.js/build/ical.js#L2067

That's the very first occurrence of `get name()`, so there seems to be a bug for this distinct piece of code.
Will report a bug later this week.
Anyway, it's too late to update this lib for ownCloud 9.0.0, how to mitigate this issue in the meantime?

**Comment by georgehrke** [comment]
reported the issue upstream: https://github.com/tchwork/jsqueeze/issues/39

**Comment by jknockaert** [comment]
@georgehrke Not sure why this one is closed. #268 is a workaround rather than a solution to the issue reported here. After an upstream fix is made available the corresponding code in OC should be updated and #268 should be reversed. Until then this ticket should be kept open imo.

**Comment by georgehrke** [comment]
The fix was to not make it break silently. Don't see a need to keep it open.

**Comment by josh4trunks** [comment]
I wonder if this solution works? =0
https://github.com/tchwork/jsqueeze/pull/41

**Comment by callmemagnus** [comment]
I patched my owncloud to revert the added error page and also patched the jsqueeze. I'm able to see my calendars without any js error.

**Comment by georgehrke** [comment]
@callmemagnus Thx a lot for testing and the actual fix at jsqueeze. Highly appreciated!

**Comment by Croydon** [comment]
Since it is now fixed, how fast can we expect an update? :)

**Comment by josh4trunks** [comment]
Since this is in core we'd need 9.0.X to update the dependency version.
https://github.com/tchwork/jsqueeze/releases/tag/v2.0.4

Hopefully by OC9.0.1?

**Comment by georgehrke** [comment]
Requested an update of JSqueeze in core: https://github.com/owncloud/core/issues/23605

**Comment by georgehrke** [comment]
> how fast can we expect an update?

Depends on whether this fix makes it into 9.0.1 or 9.0.2.
The error page will be removed with the very first version of calendar after the fix was released in core.

**Comment by georgehrke** [comment]
>  I'm able to see my calendars without any js error.

Can you see different calendar colors?
All calendars fall back to the default ownCloud blue for me.

**Comment by mmattel** [comment]
JSqueeze fix is here: https://github.com/owncloud/3rdparty/pull/266

**Comment by callmemagnus** [comment]
@georgehrke right, the calendars are all black for me too. 

I don't know if it works differently when assets are not pipelined.

I can have a look at that on Friday if nobody's available before.

For me, the most important thing was to be able to see my calendars on the web interface.

**Comment by callmemagnus** [comment]
Ok, there is still an issue with the resulting minified files.

As I can guess, in the file `calendar/js/public/app.js` we have:

```
...
2243       this._properties.displayname = displayname;
2244       this._setUpdated('displayname');
2245     },
2246     get color() {
2247       return this._properties.color;
2248     },
2249     set color(color) {
2250       this._properties.color = color;
...
```

This sadly gets minified like this:

```
  get o(){
    return this._properties.color
  },
  set o(o){
    this._properties.color=o;
    this._setUpdated('color')
  },
```

I must check if there is a way to avoid "mangling" of "color" as it is not a variable in this context.

I need to create a test case to validate this with jsqueeze.

**Comment by callmemagnus** [comment]
logged issue upstream: https://github.com/tchwork/jsqueeze/issues/43.

**Comment by callmemagnus** [comment]
Wow... to investigate I disabled JSqueeze on my install but kept the aggregation. The resulting file is _huge_ (3MB for the calendar page).
In addition to this squeeze issue, I strongly think owncloud starts to be a little obese on the js side.

**Comment by jknockaert** [comment]
Provided that the original issue is fixed (https://github.com/owncloud/3rdparty/pull/266#issuecomment-208824525), we should now reverse https://github.com/owncloud/calendar/pull/268.

**Comment by callmemagnus** [comment]
The calendar color issue remains.

**Comment by jknockaert** [comment]
Do we wait for reversing #268 till the calendar issue is fixed? In that case https://github.com/owncloud/3rdparty/pull/266 doesn't serve any purpose.

**Comment by georgehrke** [comment]
Yes, the calendar color issue still remains, anyway I would like to remove the check once owncloud/3rdparty#266 is in ownCloud 9. (probably 9.0.2)

Having the color issue is still not as bad as not being able to use asset pipeline at all.

**Comment by georgehrke** [comment]
Issue about removing the check again: https://github.com/owncloud/calendar/issues/450
Issue about the color problem: https://github.com/owncloud/calendar/issues/451

**Comment by karloluiten** [comment]
Just serving a single file with all assets (not minified) would already save lots of requests. Is this an option? Browsing NextCloud over slow networks is a pain. Thanks.
