### ISSUE TITLE
Some events not shown on Monday

### ISSUE THREAD

**Issue by jgutjahr** [owncloud/calendar#542]
### Steps to reproduce
1. Create an event on 01.08.2016 
2. Set Repeating every day, ending after 7 times
### Expected behaviour

The event should be shown every day.
### Actual behaviour

The event isn't shown on 01.08.2016 in August.

The same for the other months:
- 27.06.2016 isn't shown in July
- 30.05.2016 isn't shown in June
- 25.04.2016 isn't shown in May
- ...
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Calendar version:** (see ownCloud apps page)

**Updated from an older ownCloud or fresh install:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**

**CalDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by onny** [comment]
I'm experiencing a similair bug, might be related in case of repeating events.

### Steps to reproduce
1. Open calendar app and click on the weekly view
2. Create a new all day event and give it a name
3. Set it to repeat every year, then create
4. Event is not displayed in weekly view but its there if you change to monthly or daily view.

This bug is quite annoying for me. In the first place I thought the event isn't created at all or lost :/
I havent tested it yet on a fresh Owncloud installation.
- owncloud 9.0.2
- calendar app 1.2.2
- firefox 46.0.1

**Comment by bohni** [comment]
See also #480

**Comment by onny** [comment]
Is this bug fixed in 1.3.1? I cannot reproduce it anymore. But please verify first

**Comment by georgehrke** [comment]
I changed nothing in this regard, so this was not fixed as far as i can tell.

**Comment by onny** [comment]
Hm @jgutjahr should check it. For me its okay. It just takes a while until the events appear ...
