### ISSUE TITLE
OC 7.0.3 Shared Calendar Permission failure - full access

### ISSUE THREAD

**Issue by jester84** [owncloud/calendar#619]
Steps to reproduce:
Actual i installed a new OC 7.0.3 System and configurated the authentification to an Microsoft ADS Server via ldaps. As authentificated active directory user i shared my calendar to an active directory group without permissions like creat, delete or update, just reading.
But now all users in this active directory group are able to completly edit, 
create or delete entrys on my calendar!
It seems to happen only in this case, all other tests like sharing between users from ads, or between lokal users and lokal groups are doing fine without that problem.

Server configuration
Operating system: Ubuntu LTS Server 12.04.05
Web server: Apache2
Database: MySQL
ownCloud version: 7.0.3 (stable)
Updated from an older ownCloud or fresh install: fresh installation
Are you using encryption: yes

Client configuration
Browser: Firefox
Calendar client: Firefox Webbrowser
Operating system: Ubtuntu Desktop 12.04

**Comment by cedric-dufour** [comment]
Also experimenting group <-> users permissions inconsistencies, for calendars AND files (user could edit TXT file even though owner removed edit permission for the group)
All groups and users (~300) are LDAP-based.
No name conflict between sharer calendar-or-file name and users; per-user share_type=2 entries get created none-the-less (which is scary in terms of scalability).
Deleting share_type=2 entries makes shared object disappear from users view (web or caldav), even though share_type=1 (group-level) entry remains. (PS: is there some cache I should clear after modifying the DB?)
OC 7.0.4-3 Debian/Wheezy from official OC repository.
Hope this help,
Best

**Comment by georgehrke** [comment]
> AND files (user could edit TXT file even though owner removed edit permission for the group)

please report a dedicated bug report in the core repo.

**Comment by georgehrke** [comment]
@schiesbn Did you find time to further dig into this from a sharing api point of view?

**Comment by JB1985** [comment]
Fixed in owncloud 8.0.0?

**Comment by georgehrke** [comment]
no, otherwise this issue would be marked as closed.

**Comment by antondollmaier** [comment]
I just witnessed this bug as well:

* OwnCloud 7.0.4
* no LDAP
* local OC-Groups
* sharing my calendar to a group with no further permissions (no edit, no delete, no move, ... - just read)

Users in the target group are now able to create new as well as delete existing events.

This should probably not happen at all.

**Comment by warhog** [comment]
Really annoying that nothing is happening here.
This one's open for three months now!

**Comment by antondollmaier** [comment]
Updated to OC8. Now the group permissions are working as expected.

**Comment by JB1985** [comment]
On my testing OC8 is working the permissions too. Seems to be fixed.

Any idea how to get back all share_types = 2? Because i have delete it for working the permissions on my production OC, without delete the share and creating new?

**Comment by cedric-dufour** [comment]
Can a OC developer confirm this has been fixed in OC8 (so far, we have contradictory information) ?
@JB1985 From my understanding, share_types=2 ought to be created only when there are some name conflicts on the shared resource. They should not be created unless there is such conflict, which is fortunate for those of us who have several hundred users groups. Can a OC developer confirm this is true ?
Thanks and have all a good week-end

**Comment by c-holtermann** [comment]
Is there progress on this issue ? I can't upgrade to OC 8 at the moment without quite a lot of effort. I'm using OC 7.0.5

**Comment by georgehrke** [comment]
I didn't fix it for ownCloud 8. So apparently it was an issue in core that was fixed with version 8.
no update planned for owncloud 7, please update
